[package]
name = "imgsz-rs"
version = "0.1.0"
edition = "2021"
license-file="./COPYING"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
byteorder = "1"

